port:             4567
proxy: 
phone_number:     
api_key:
secret_key:
registration_id:  
tokens_file:      tokens
FQDN:             https://api.att.com

tokens_file:      tokens
subject_file:     subject.txt
phones_file:      phones.txt
coupon_file:      images/coupon.jpg

listener_url:     http://localhost:4567/mmslistener
images_url:       http://localhost:4567
momms_data_dir:   MoMmsData
momms_image_dir:  MoMmsImages
