port:             4567
proxy: 
api_key:          
secret_key:       
FQDN:             https://api.att.com
redirect_url:     http://localhost:4567

help_link:  http://localhost:4567/help
download_link:  http://localhost:4567/download
source_link:  http://localhost:4567/source
